site_name: Juan José Ruiz | Work Profile

nav:
  - Intro: index.md
  - Bio: bio.md
  - 'Skills':
    - 'Top': 'top-skills.md'
    - 'Expert': 'expert-skills.md'
    - 'Advanced': 'advanced-skills.md'
    - 'Intermediate': 'intermediate-skills.md'
    - 'Novice': 'novice-skills.md'
    - 'Pending Assessment' : 'pa-skills.md'
  - Certifications: certifications.md
  - 'Project Assignments':
    - Current: 'current-project-assignments.md'
    - Past: 'past-project-assignments.md'
  - Experience: experience.md
  - Education: education.md
  - Contact: contact-page.md

theme:
  name: material
  logo: images/wizeline_isotype.png
  
extra_css:
  - css/extra.css