site_name: Juan José Ruiz | Work Profile

nav:
  - Intro: index.md
  - Bio: bio.md
  - Contact: contact-page.md

theme:
  name: material
  logo: images/wizeline_isotype.png
  
extra_css:
  - css/extra.css